#!/bin/bash


# Run this script from base directory of StarExec job output containing subdirectories for each of the sygus comp 2019 job outputs.
# For 2019, this should be run in https://github.com/SyGuS-Org/tools/tree/master/2019/results/results_tgz/ with all tgz expanded.

# Requires: mk_table in current directory.



for DIR in */ ; do
    BENCHDIR="$ROOTBENCHDIR/$DIR"
    TRACKNAME=${DIR%?};
    echo "Making tables for track $TRACKNAME ..."
    ./mk_table ../results-txt/results-$TRACKNAME.txt > ../results-txt/$TRACKNAME.csv
    if [ ! -f mk_table_summary.tmp ];
    then
      echo "Warning: Missing output file mk_table_summary.tmp"
    fi
    echo "mv mk_table_summary.tmp ../results-txt/$TRACKNAME-summary.csv"
    mv mk_table_summary.tmp ../results-txt/$TRACKNAME-summary.csv
done
