#!/bin/bash


# Run this script from base directory of StarExec job output containing subdirectories for each of the sygus comp 2019 job outputs.
# For 2019, this should be run in https://github.com/SyGuS-Org/tools/tree/master/2019/results with all tgz expanded.

# Requires: clean_starexec_out, process_solver_results, process_result, process_track_results, SynthLib2Tester in path.

ROOTBENCHDIR=$1

echo "Root benchmark directory set to $ROOTBENCHDIR"

if [ ! -d "$ROOTBENCHDIR" ];
then
  echo "Error: Bad root benchmark directory specified $ROOTBENCHDIR"
  exit 1
fi

# $ROOTBENCHDIR is path to sygus benchmarks over all tracks.
# For 2019, this should be the directory https://github.com/SyGuS-Org/benchmarks/tree/master/comp/2019.


for DIR in */ ; do
    BENCHDIR="$ROOTBENCHDIR/$DIR"
    TRACKNAME=${DIR%?};
    cd $DIR;
    echo "Analyzing track $TRACKNAME ..."
    #echo "[debug] benchmark directory $BENCHDIR"
    process_track_results $BENCHDIR > ../results-txt/results-$TRACKNAME.txt
    #mk_table ../results-txt/results-$TRACKNAME.txt > ../results-txt/$TRACKNAME.csv
    cd ..;
done
